# file generated by setuptools-scm
# don't change, don't track in version control

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

__version__ = version = "0.1.2.dev3"
__version_tuple__ = version_tuple = (0, 1, 2, "dev3")
__commit_id__ = commit_id = "g4a237153d"
